#!/usr/bin/env python3

import os

from hammer.vlsi import CLIDriver, HammerTool, HammerToolHookAction

from typing import Dict, Callable, Optional, List

from hammer.technology.sky130 import SKY130Tech

def write_dyn_report_hook(x: HammerTool) -> bool:
    x.verbose_append("set_power_include_file power.inc")
    power_inc_path = f"{x.run_dir}/power.inc"
    with open(power_inc_path, "w") as f:
         f.writelines("report_power -outfile power.rpt")
    return True

class Eecs251bDriver(CLIDriver):
    def get_extra_par_hooks(self) -> List[HammerToolHookAction]:
        extra_hooks = [
            # Default set of steps can be found in the CAD tool plugin's __init__.py

            # make_pre_insertion_hook will execute the custom hook before the specified step
            # SYNTAX: make_pre_insertion_hook("EXISTING_STEP", INSERTED_HOOK)
            # HammerTool.make_pre_insertion_hook("route_design", example_add_fillers),

            # make_post_insertion_hook will execute the custom hook after the specified step
            # HammerTool.make_post_insertion_hook("init_design", example_tool_settings),

            # make_replacement_hook will replace the specified step with a custom hook
            # HammerTool.make_replacement_hook("place_tap_cells", example_place_tap_cells),

            # make_removal_hook will remove the specified step from the flow
            HammerTool.make_removal_hook("place_bumps"),
            # HammerTool.make_post_insertion_hook("route_design", force_iquantus_hook),

            # The target step in any of the above calls may be a default step or another one of your custom hooks
        ]
        return extra_hooks
    def get_extra_power_hooks(self) -> List[HammerToolHookAction]:
        return [HammerTool.make_pre_insertion_hook("active_power", write_dyn_report_hook)]

if __name__ == '__main__':
    Eecs251bDriver().main()
